services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: prompt_builder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ../..
      dockerfile: infra/docker/backend.Dockerfile
    environment:
      FLASK_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: prompt_builder
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ../..
      dockerfile: infra/docker/frontend.Dockerfile
    environment:
      VITE_BACKEND_URL: http://backend:5000
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pgdata:


