services:
  db:
    image: postgres:14-alpine
    env_file:
      - ../../.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ../..
      dockerfile: infra/docker/backend.Dockerfile
    env_file:
      - ../../.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5001:5000"

  frontend:
    build:
      context: ../..
      dockerfile: infra/docker/frontend.Dockerfile
    env_file:
      - ../../.env
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pgdata:


